image: docker:git
#image: registry.datana.ru/alpine-java-docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_VERSION: 0.1.1
  IMAGE_NAME: $DOCKER_REGISTRY_HOST/datana_smart_alerts

stages:
  - deploy

before_script:
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug

deploy:
  stage: deploy
  script:
    - docker info
    - echo "-t $IMAGE_NAME:$IMAGE_VERSION -t $IMAGE_NAME:latest "
    #        - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS" "$DOCKER_REGISTRY_HOST"
    - echo "$DOCKER_REGISTRY_PASS" | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY_HOST
    - docker build -t $IMAGE_NAME:$IMAGE_VERSION -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$IMAGE_VERSION
    - docker push $IMAGE_NAME:latest
    - docker logout $DOCKER_REGISTRY_HOST
  only:
    - dev
    - master

after_script:
  - echo "End CI"
